name: learn_9_pract
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
